---
- hosts: localhost
  tasks:
  - name: start docker service
    service:
      name: docker
      state: started
      enabled: true
  - name: deploy test application
    command: sudo docker run -it -d -p 8888:8888 ambikagollapudi567/batch10:15.0
  handlers:
  - name: run update
    apt:
      update_cache: yes
